spring:
  cloud:
    function:
      definition: logCreekMeasurements
    stream:
      function:
        bindings:
          logCreekMeasurements-in-0: input
      bindings:
        input:
          destination: creek-data
          group: foo
