spring:
  cloud:
    function:
      definition: creekDataSupplier
    stream:
      poller:
        fixed-delay: 15000
      function:
        bindings:
          creekDataSupplier-out-0: output
      bindings:
        output:
          destination: usgs-data
          group: foo