spring:
  cloud:
    function:
      definition: generateReport|log
    stream:
      function:
        bindings:
          generateReportlog-in-0: input
      bindings:
        input:
          destination: creek-data
          group: log
