spring:
  cloud:
    function:
      definition: generateReport|sms
    stream:
      function:
        bindings:
          generateReportsms-in-0: input
      bindings:
        input:
          destination: creek-data
          group: sms
