spring:
  cloud:
    function:
      definition: creekMeasurementRepository
    stream:
      function:
        bindings:
          creekMeasurementRepository-in-0: input
      bindings:
        input:
          destination: creek-data
          group: foo-repo
  sql:
    init:
      mode: always
server:
  port: 0

